### ISSUE TITLE
Conditional for enabling/disabling the security-hub module entirely

### ISSUE THREAD

**Issue by riwiki** [centriascolocation/terraform-aws-security#3]
As a developer, I want to be able to disable the security-hub module with all its resources, so I can include it in a multi-workspace setup where the security-hub is created only in the workspace that relates to my AWS master account, while all other security-related modules are deployed in all accounts i.e. all workspaces.

**Comment by michaelkrieg** [comment]
This is done in master branch now. We will include this in the next release / tag as well.
